version: "3.3"
services:
  backend:
    image: gitlab.praktikum-services.ru:5050/<username>/sausage-store/sausage-backend:${VERSION}
    container_name: sausage-backend
    environment:
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_DATABASE}
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
      SPRING_CLOUD_VAULT_TOKEN: ${VAULT_TOKEN}
    networks:
      - sausage-store
  backend-report:
    image: gitlab.praktikum-services.ru:5050/<username>/sausage-store/backend-report:${BACKEND_REPORT_VERSION}
    container_name: backend-report
    environment:
      SPRING_CLOUD_VAULT_TOKEN: ${VAULT_TOKEN}
    networks:
      - sausage-store
  frontend:
    image: gitlab.praktikum-services.ru:5050/<username>/sausage-store/sausage-frontend:${VERSION}
    container_name: sausage-frontend
    ports:
      - "80:80"
    networks:
      - sausage-store
  vault:
    image: vault
    container_name: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID}
      VAULT_SERVER: ${VAULT_SERVER}
      VAULT_ADDR: ${VAULT_ADDR}
    networks:
      - sausage-store

networks:
  sausage-store:
