version: "3.4"
services:
  backend:
    image: gitlab.praktikum-services.ru:5050/russianvoodoo4/sausage-store/sausage-backend:${CI_COMMIT_SHA}
    restart: always
    expose:
      - "8080"
    healthcheck:
      test: curl --fail -s http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 6 
    build:
      context: backend
      dockerfile: Dockerfile
      args: 
        VERSION: ${VERSION}
    environment:
      VAULT_PORT: ${VAULT_PORT}
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_HOST: ${VAULT_HOST}
      VIRTUAL_HOST: test2

      # SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      # SPRING_DATASOURCE_URL: jdbc:postgresql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_DATABASE}
      # SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
      # SPRING_CLOUD_VAULT_TOKEN: ${VAULT_TOKEN}
    networks:
      - sausage-store
  backend-report:
    image: gitlab.praktikum-services.ru:5050/russianvoodoo4/sausage-store/backend-report:${CI_COMMIT_SHA}
    build:
      context: backend-report
      dockerfile: Dockerfile
      args: 
        VERSION: ${VERSION}
    container_name: backend-report
    environment:
      VAULT_PORT: ${VAULT_PORT}
      VAULT_TOKEN: ${VAULT_TOKEN}
      VAULT_HOST: ${VAULT_HOST}
    networks:
      - sausage-store
  frontend:
    image: gitlab.praktikum-services.ru:5050/russianvoodoo4/sausage-store/sausage-frontend:${CI_COMMIT_SHA}
    build:
      context: frontend
      dockerfile: Dockerfile
      args: 
        VERSION: ${VERSION}
    container_name: sausage-frontend
    environment:
      - DEFAULT_HOST=test2
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
    networks:
      - sausage-store
  # vault:
  #   image: vault
  #   container_name: vault
  #   environment:
  #     VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID}
  #     VAULT_SERVER: ${VAULT_SERVER}
  #     VAULT_ADDR: ${VAULT_ADDR}
  #   networks:
  #     - sausage-store

networks:
  sausage-store: